version: '3.7'
services:
  react-std:
   build:
      context: ../../reactapp/testapp/. # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: ../../reactapp/testapp/Dockerfile
   image: "react-std:latest" 
   ports:
      - "3000:3000"
   expose:
      - "3000"   
   depends_on:
      - stdmgmt
   networks:
      std-net:
        ipv4_address: 10.5.0.5
    
  stdmgmt:
     
    build:
      context: . # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    image: "stdmgmt:latest"
    ports:
      - "8080:8080"
    expose:
      - "8080"   
    networks:
      std-net:
        ipv4_address: 10.5.0.6
      
networks:
  std-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
       
     